# Site settings
title: Juicebox
company: Juicebox Systems, Inc.
logo_path: /assets/images/juicebox-logo.png 

# SEO
tagline: An open-source encryption key recovery protocol
description: Juicebox is an open-source encryption key recovery protocol that provides high security coupled with a user-friendly design, to make encryption further accessible to larger numbers of people. Juicebox leverages programmable HSMs, distributed cryptography, and a user-friendly PIN-based recovery process to simplify key recovery without compromising security.
twitter:
  username: juicebox_xyz
  card: summary

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/seo-logo.png

collections:
  posts:
    permalink: /blog/:title
    sort_by: date

contributors:
  - name: Alex Bochannek
    github: abochannek
  - name: Simon Fell
    github: superfell
  - name: Moxie Marlinspike
    github: moxie0
  - name: Diego Ongaro
    github: ongardie
  - name: Daniela Perlein
    github: daniela-juicebox
    site: https://danielaperlein.com
  - name: Nora Trapp
    github: imperiopolis

twitter: juicebox_xyz
github: juicebox-systems

plugins:
  - jekyll-feed

google_analytics:

# Build settings
theme: minima
markdown: kramdown

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
